import forms from '@tailwindcss/forms'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#dde4e6',
        'on-background': '#2f3430',
        'on-error': '#fff7f6',
        'error': '#9f403d',
        'background': '#faf9f6',
        'surface-variant': '#e0e4de',
        'on-primary-container': '#4c5355',
        'inverse-on-surface': '#9d9d9a',
        'secondary': '#5f604d',
        'on-secondary-container': '#525341',
        'tertiary': '#565f78',
        'on-primary-fixed-variant': '#565d5f',
        'inverse-primary': '#f1f8fa',
        'on-primary-fixed': '#394043',
        'secondary-fixed-dim': '#d6d6be',
        'on-tertiary-fixed-variant': '#4d566f',
        'tertiary-fixed-dim': '#c2cbe9',
        'secondary-container': '#e4e4cc',
        'inverse-surface': '#0d0f0d',
        'surface-container-high': '#e6e9e4',
        'outline-variant': '#afb3ae',
        'surface-dim': '#d6dbd5',
        'on-secondary': '#fbfae1',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#f9f8ff',
        'secondary-fixed': '#e4e4cc',
        'surface': '#faf9f6',
        'on-secondary-fixed-variant': '#5b5d4a',
        'on-primary': '#f2f9fb',
        'surface-container-highest': '#e0e4de',
        'on-tertiary-container': '#434c65',
        'error-dim': '#4e0309',
        'on-secondary-fixed': '#3f412f',
        'primary-fixed-dim': '#cfd6d8',
        'primary-container': '#dde4e6',
        'surface-tint': '#586062',
        'surface-container': '#edeeea',
        'tertiary-container': '#d0d9f7',
        'on-error-container': '#752121',
        'tertiary-fixed': '#d0d9f7',
        'on-tertiary-fixed': '#303951',
        'secondary-dim': '#535442',
        'on-surface': '#2f3430',
        'error-container': '#fe8983',
        'on-surface-variant': '#5c605c',
        'primary-dim': '#4c5456',
        'tertiary-dim': '#4a536b',
        'surface-container-low': '#f4f4f0',
        'primary': '#586062',
        'outline': '#777c77',
        'surface-bright': '#faf9f6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [forms],
}
